const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.ScriptsInEvents.Folhafase1_Event17_Act1,
		C3.ScriptsInEvents.Folhafase1_Event18_Act1,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.CreateObject,
		C3.ScriptsInEvents.Folhacastelo_Event2_Act1,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Cnds.OnCreated
	];
};
self.C3_JsPropNameTable = [
	{cenarioPassagem: 0},
	{testeAgua: 0},
	{testeAgua2: 0},
	{testeAgua3: 0},
	{portaC: 0},
	{miniilha: 0},
	{cenario: 0},
	{fundoInicio: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Plataforma: 0},
	{Sung: 0},
	{Teclado: 0},
	{mulher: 0},
	{Sólido: 0},
	{chaoInicio: 0},
	{FundoFase1: 0},
	{Chefao: 0},
	{Direcao: 0},
	{General: 0},
	{direcao: 0},
	{direcao2: 0},
	{Piscar: 0},
	{Minotauro1: 0},
	{MInotaura2: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{BolaFogo: 0},
	{spritePortalinicio: 0},
	{portalInimigos: 0},
	{Mouse: 0},
	{Áudio: 0},
	{sensor_direita: 0},
	{sensor_esquerda: 0},
	{contatoSeraphina: 0},
	{portalparaCastelo: 0},
	{portalPassagem: 0},
	{explosao: 0},
	{Sprite: 0},
	{vidas: 0},
	{PlanoDeFundoEmBlocos: 0},
	{portalIrCastelo: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{FonteDeSprites: 0},
	{Fixar: 0},
	{Sprite2: 0},
	{btnAgain: 0},
	{btnSair: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{btnHistoria: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{jogaNovamente: 0},
	{Sair: 0},
	{Sprite8: 0},
	{GeneralFinal: 0},
	{Sprite9: 0},
	{historia: 0},
	{paraPular: 0},
	{Sprite10: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{historiaPergunta: 0},
	{Avancar: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{Texto: 0},
	{FonteDeSprites2: 0},
	{PlanoDeFundoEmBlocos7: 0},
	{habilidade: 0},
	{btnINICIAR: 0},
	{PlanoDeFundoEmBlocos8: 0},
	{chefe: 0},
	{Dano1: 0},
	{Dano2: 0},
	{matar: 0}
];

self.InstanceType = {
	cenarioPassagem: class extends self.ITiledBackgroundInstance {},
	testeAgua: class extends self.ITiledBackgroundInstance {},
	testeAgua2: class extends self.ITiledBackgroundInstance {},
	testeAgua3: class extends self.ITiledBackgroundInstance {},
	portaC: class extends self.ISpriteInstance {},
	miniilha: class extends self.ISpriteInstance {},
	cenario: class extends self.ITiledBackgroundInstance {},
	fundoInicio: class extends self.ITiledBackgroundInstance {},
	Sung: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	mulher: class extends self.ISpriteInstance {},
	chaoInicio: class extends self.ISpriteInstance {},
	FundoFase1: class extends self.ITiledBackgroundInstance {},
	Chefao: class extends self.ISpriteInstance {},
	General: class extends self.ISpriteInstance {},
	Minotauro1: class extends self.ISpriteInstance {},
	MInotaura2: class extends self.ISpriteInstance {},
	BolaFogo: class extends self.ISpriteInstance {},
	spritePortalinicio: class extends self.ISpriteInstance {},
	portalInimigos: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	sensor_direita: class extends self.ISpriteInstance {},
	sensor_esquerda: class extends self.ISpriteInstance {},
	contatoSeraphina: class extends self.ISpriteInstance {},
	portalparaCastelo: class extends self.ISpriteInstance {},
	portalPassagem: class extends self.ISpriteInstance {},
	explosao: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	vidas: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	portalIrCastelo: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	btnAgain: class extends self.ISpriteInstance {},
	btnSair: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	btnHistoria: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	jogaNovamente: class extends self.ISpriteInstance {},
	Sair: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	GeneralFinal: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	historia: class extends self.ITextInstance {},
	paraPular: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	historiaPergunta: class extends self.ITextInstance {},
	Avancar: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	Texto: class extends self.ITextInstance {},
	FonteDeSprites2: class extends self.ISpriteFontInstance {},
	PlanoDeFundoEmBlocos7: class extends self.ITiledBackgroundInstance {},
	habilidade: class extends self.ITextInstance {},
	btnINICIAR: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos8: class extends self.ITiledBackgroundInstance {}
}